Create table EMPR
(MATR CHAR (6) primary key,
NOME VARCHAR (12) not null,	
SOBRENOME VARCHAR (15) not null,
DEPT CHAR(3),
FONE CHAR(14),
DINADIM DATE,
CARGO CHAR(10),
NIVELED	INT(2),
SEXO	CHAR(1),
DATANAS	 DATE,
SALARIO	 decimal(9,2),
BONUS	decimal(9,2),
COMIS	decimal(9,2),
FOREIGN KEY(DEPT) REFERENCES DEPT(DCODIGO)
);

Create table DEPT
(DCODIGO	CHAR(3) primary key,
DNOME		VARCHAR(36),
GERENTE		CHAR (6),
DSUPER		CHAR(3),
FOREIGN KEY(GERENTE) REFERENCES EMPR(MAT),
FOREIGN KEY(DSUPER) REFERENCES DEPT(DCODIGO)
);
Create table PROJETO
(PCODIGO  	CHAR(6) PRIMARY KEY,
PNOME		VARCHAR(24),
DCODIGO		CHAR(3),
RESP 		CHAR(6),
EQUIPE		INT(5),
DATAINI		DATE, 
DATAFIM		DATE,
PSUPER		CHAR(6),
FOREIGN KEY(DCODIGO) REFERENCES DEPT(DCODIGO),
FOREIGN KEY(RESP) REFERENCES EMPR(MATR),
FOREIGN KEY(PSUPER) REFERENCES PROJETO(PCODIGO)
);

Create table TrabalhaEM(
MATR char(6),
PCODIGO char(6),
HORASALOCACAO INT,
PRIMARY KEY(MATR,PCODIGO),
FOREIGN KEY(PCODIGO) REFERENCES PROJETO(PCODIGO),
FOREIGN KEY(MATR) REFERENCES EMPR(MATR)
);
